### ISSUE TITLE
Create Github workflows.

### ISSUE THREAD

**Issue by antweiss** [Spiroman/terraform-gcp#2]
Create the following [github action workflows](https://docs.github.com/en/actions):

1.  A scheduled workflow (08:00AM) to:

-  call terraform and create a cluster with default values (only the project_id should be passed in to point at what you have in your GCP account now)
- clone https://github.com/otomato-gh/maskshop
- extract newly created cluster creds and call helm on https://github.com/otomato-gh/maskshop/tree/master/maskshop-chart to install it in the cluster

2. A scheduled workflow (08:00PM) to
- call terraform to destroy the default cluster

For google creds, etc. - here's an example
```
name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: devops@texel.live
        service_account_key: ${{ secrets.GKE_SA_KEY }}

    - name: Set up helm
      run: |
        curl -L https://git.io/get_helm.sh | bash
    - name: Delete releases in belive
    # if there are no releases we still continue
      continue-on-error: true
      run: |
        gcloud container clusters get-credentials belive-cluster --zone asia-northeast1-a --project $GKE_PROJECT
        helm ls --output=json | jq '.Releases[] | select( .Namespace != "noevir") | select( .Name | contains("prom") | not ) | select( .Chart | contains("kong") | not) | select( .Name | contains("coviewssl") | not) | .Name' | xargs helm delete --purge
    
```
